language: go

go:
  - 1.5.1

env:
    - GIMME_OS=linux GIMME_ARCH=amd64

go_import_path: github.com/dapeng-fu/GoTest

install:
  - go get -u github.com/beego/bee
  - go get -u github.com/astaxie/beego
  - echo "123"


